In [15]:
import tensorflow as tf

# One Feature Node

In [16]:
class One_Feature_Node:
    def __init__(self):
        self.w = tf.Variable([[0.1]])
        self.b = tf.Variable([[0.5]])

    def __call__(self, x):
        return self.get_output(x)
    
    def get_output(self, x):
        out = tf.matmul(x, self.w)
        print("matmul result: ", out.numpy())
        out = tf.add(out, self.b)
        print("adding bias relsult: ", out.numpy())
        out = tf.math.sigmoid(out)
        print("sigmoid result: ", out.numpy())
        
        return out

In [17]:
# Single Input
x = tf.constant([[1.0]])

one_feature_node = One_Feature_Node()
one_feature_node(x)

matmul result:  [[0.1]]
adding bias relsult:  [[0.6]]
sigmoid result:  [[0.64565635]]


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.64565635]], dtype=float32)>

# Two Features Node

In [18]:
class Two_Features_Node:
    def __init__(self):
        self.w = tf.Variable([[0.1], [0.2]])
        self.b = tf.Variable([[0.5]])

    def __call__(self, x):
        return self.get_output(x)
    
    def get_output(self, x):
        out = tf.matmul(x, self.w)
        print("matmul result: ", out.numpy())
        out = tf.add(out, self.b)
        print("adding bias result: ", out.numpy())
        out = tf.math.sigmoid(out)
        print("sigmoid result: ", out.numpy())

        return out

In [19]:
# Multi Features Single Input (Two Features for one data)
x1 = tf.constant([[1.0, 2.0]])

two_features_node = Two_Features_Node()
two_features_node(x1)

# 한마디로, 여러 개 입력에 각각의 가중치 곱해서 더하고 마지막에 편향값 더해서 시그모이드 돌리는 것임

matmul result:  [[0.5]]
adding bias result:  [[1.]]
sigmoid result:  [[0.7310586]]


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.7310586]], dtype=float32)>

# N inputs for Two Features Node

In [20]:
# Multi Input Data (3 Samples)
x2= tf.constant([[1.0, 2.0], [2.0, 3.0], [4.0, 5.0]])

two_features_node(x2)

matmul result:  [[0.5]
 [0.8]
 [1.4]]
adding bias result:  [[1. ]
 [1.3]
 [1.9]]
sigmoid result:  [[0.7310586]
 [0.785835 ]
 [0.8698915]]


<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.7310586],
       [0.785835 ],
       [0.8698915]], dtype=float32)>

# tf.function speed check

tf.function decoration put your python onto autograph

This enables faster execution, running on GPU or TPU, or exporting to SavedModel.

-> 한마디로 tensorflow에 맞게 최적화하여 실행 속도를 ㅈㄴ 높인다는 뜻이다.

In [21]:
import timeit

In [22]:
class Two_Features_Node2:
    def __init__(self):
        self.w = tf.Variable([[0.1], [0.2]])
        self.b = tf.Variable([[0.5]])

    def __call__(self, x):
        return self.get_output(x)
    
    def get_output(self, x):
        for i in range(50):
            out = tf.matmul(x, self.w)
            out = tf.add(out, self.b)
            out = tf.math.sigmoid(out)

        return out
    
    @tf.function
    def get_out_faster(self, x):
        for i in range(50):
            out = tf.matmul(x, self.w)
            out = tf.add(out, self.b)
            out = tf.math.sigmoid(out)

        return out

In [23]:
two_features_node2 = Two_Features_Node2()

get_out_without_tf_function_timeit = timeit.timeit(lambda: two_features_node2.get_output(x2), number = 300)
get_out_with_tf_function_timeit = timeit.timeit(lambda: two_features_node2.get_out_faster(x2), number = 300)
time_diff = round(get_out_without_tf_function_timeit / get_out_with_tf_function_timeit, 1)

In [24]:
print("get_output_faster(@tf.function) is " + str(time_diff) + " times faster than get_output_without_tf_function!")

get_output_faster(@tf.function) is 16.5 times faster than get_output_without_tf_function!
