In [30]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, SimpleRNN, TimeDistributed
from tensorflow.keras.models import Model, Sequential
import numpy as np

# RNN Cell Practice

In [31]:
# input shape
inputs = Input(shape = (1, 2))
# output shape, return state, use tanh as activation function
output, state = SimpleRNN(3, return_state = True, activation = 'tanh')(inputs)
model = Model(inputs = inputs, outputs = [output, state])

In [32]:
# test input
data = np.array([[ [1, 2] ]])
# print output, state
output, state = model.predict(data)
print("output:", output)
print("state:", state)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step
output: [[-0.7750771  -0.9951801  -0.27593943]]
state: [[-0.7750771  -0.9951801  -0.27593943]]


In [33]:
# weights for input
model.layers[1].weights[0]

<Variable path=simple_rnn_6/simple_rnn_cell/kernel, shape=(2, 3), dtype=float32, value=[[ 0.472579   -1.0017076  -0.5711648 ]
 [-0.7527498  -1.0055805   0.14394164]]>

In [34]:
# weights for state
model.layers[1].weights[1]

<Variable path=simple_rnn_6/simple_rnn_cell/recurrent_kernel, shape=(3, 3), dtype=float32, value=[[ 0.06851089  0.26684555  0.9613011 ]
 [-0.28074524  0.9297829  -0.23808809]
 [ 0.957334    0.2535691  -0.13861585]]>

In [35]:
# bias
model.layers[1].weights[2]

<Variable path=simple_rnn_6/simple_rnn_cell/bias, shape=(3,), dtype=float32, value=[0. 0. 0.]>

# sequence tagging example

In [36]:
John = [1, 0, 0]
loves = [0, 1, 0]
Jane = [0, 0, 1]

X = np.array([
    [ John, loves, Jane ],
    [ Jane, loves, John ]
]).astype(np.float32)

S = [0] # subject
V = [1] # verb
O = [2] # object
y = np.array([[S, V, O], [S, V, O]]).astype(np.float32)

In [37]:
# input shape
inputs = Input(shape = (3, 3))
# output shape, return state, return sequence
output, state = SimpleRNN(3, return_state = True, return_sequences = True)(inputs)
model = Model(inputs = inputs, outputs = [output, state])

In [38]:
# print output, state
output, state = model.predict(X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 293ms/step


In [39]:
print("John loves Jane:", output[0])
print("Jand loves John:", output[1])

John loves Jane: [[ 0.24439369  0.39654818  0.15325832]
 [-0.5959973  -0.5941912   0.75543123]
 [-0.8222831   0.31614372 -0.20502059]]
Jand loves John: [[-0.519067    0.18610547  0.63367164]
 [-0.6964095  -0.28942487  0.16022561]
 [ 0.29683754  0.5154946  -0.5367173 ]]


In [40]:
# the state value is same with the last output
print("John loves Jane:", state[0])
print("Jand loves John:", state[1])

John loves Jane: [-0.8222831   0.31614372 -0.20502059]
Jand loves John: [ 0.29683754  0.5154946  -0.5367173 ]


In [42]:
model = Sequential()
model.add(SimpleRNN(3, input_shape = (3, 3), return_sequences = True))
model.add(TimeDistributed(Dense(3, activation = 'softmax')))
model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam')
print(model.summary())

model.fit(X, y, epochs = 2000, verbose = 1)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_9 (SimpleRNN)        │ (None, 3, 3)           │            21 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed_2              │ (None, 3, 3)           │            12 │
│ (TimeDistributed)               │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 33 (132.00 B)

 Trainable params: 33 (132.00 B)

 Non-trainable params: 0 (0.00 B)

None
Epoch 1/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 1.1710
Epoch 2/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 1.1695
Epoch 3/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 1.1680
Epoch 4/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 1.1664
Epoch 5/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 1.1649
Epoch 6/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 1.1634
Epoch 7/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 1.1619
Epoch 8/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 1.1604
Epoch 9/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 1.1590
Epoch 10/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 1.1575
Epoch 11/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 1.1560
Epoch 12/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 1.1546
Epoch 13/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - loss: 1.1531
Epoch 14/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - loss: 1.1517
Epoch 15/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 1.1503

In [43]:
model.fit(X, y, epochs = 500, verbose = 1)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 0.0196
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.0196
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.0196
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0196
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 0.0196
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 0.0195
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 0.0195
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 0.0195
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 0.0195
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0195
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 0.0194
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step - loss: 0.0194
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.0194
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 0.0194
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 0.0194
Epoch 16/500
1/1

In [44]:
model.fit(X, y, epochs = 1000, verbose = 1)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - loss: 0.0122
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 637ms/step - loss: 0.0122
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - loss: 0.0122
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 247ms/step - loss: 0.0122
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 0.0122
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 0.0122
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - loss: 0.0122
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0122
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0122
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 0.0121
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 0.0121
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 0.0121
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0121
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 0.0121
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.01

In [45]:
model.save("RNN_tf.keras")

In [46]:
from tensorflow.keras.models import load_model
model = load_model("RNN_tf.keras")

In [47]:
result = model.predict(X, verbose = 0)

In [48]:
result

array([[[0.99344516, 0.00447946, 0.00207542],
        [0.00318787, 0.99388015, 0.00293195],
        [0.0032975 , 0.00197179, 0.9947307 ]],

       [[0.99468887, 0.00335262, 0.00195853],
        [0.00314108, 0.99394107, 0.00291786],
        [0.00325567, 0.00198206, 0.99476236]]], dtype=float32)

In [51]:
# check the result

# 0 : Subject
# 1 : Verb
# 2 : Object
np.argmax(result, axis = 1)


array([[0, 1, 2],
       [0, 1, 2]])