In [1]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, ConvLSTM2D, BatchNormalization, Conv3D
import tensorflow as tf

In [2]:
# 공간 하나짜리를 만들어, 거에 공간 7개짜리를 넣어
input_shape = (1, 7)
x = tf.random.normal(input_shape)
x

<tf.Tensor: shape=(1, 7), dtype=float32, numpy=
array([[ 0.9990124 , -0.961711  , -0.5821762 ,  0.49547455, -0.09489138,
         0.6461802 ,  0.21917307]], dtype=float32)>

In [3]:
# 공간 4개를 만들고 거기에 각각 7개를 넣고 또 28개를 넣고, 또 28개를 넣고, 또 1개를 넣어
input_shape = (4, 7, 28, 28, 28, 1)
x = tf.random.normal(input_shape)

In [4]:
x[0][0][0][0]

<tf.Tensor: shape=(28, 1), dtype=float32, numpy=
array([[-0.26088864],
       [ 0.31501073],
       [ 0.21190175],
       [-0.01877998],
       [-1.7134632 ],
       [-0.5096753 ],
       [-0.7354338 ],
       [ 0.4725992 ],
       [ 0.7279881 ],
       [-1.1847614 ],
       [ 0.5609031 ],
       [ 0.6957591 ],
       [-0.12316807],
       [-0.08211333],
       [-1.5113832 ],
       [-0.6691962 ],
       [ 1.1140531 ],
       [-1.342315  ],
       [-1.012869  ],
       [ 1.5606835 ],
       [ 0.92120034],
       [ 0.6077074 ],
       [-1.1489134 ],
       [-0.19200987],
       [-0.48955372],
       [-1.1324242 ],
       [-0.36288708],
       [-0.16290691]], dtype=float32)>

In [5]:
# 앞에서 공간 생성과 똑같음, 그러나 Conv3D에서는 다른 의미로 해석됨
# 4 -> 배치크기(한 번에 처리할 데이터 샘플의 수)
# (10,10,10) -> 각 샘풀의 3차원 데이터 크기
# 128 -> 데이터의 채널 수
x = tf.random.normal((4, 10, 10, 10, 128))
# 32 -> 출력 채널의 수이자 필터의 개수, 즉 32개의 필터가 각각 수행되며 32개의 특징 맵이 나옴
# (3,4,5) -> 필터가 (3,4,5) 크기라는 의미
y = Conv3D(32, (3,4,5), activation='relu')(x)

In [6]:
print(
    x[0].shape,
    x[1].shape,
    x[2].shape,
    x[3].shape,
    "\n"+f"{x.shape}"
)

(10, 10, 10, 128) (10, 10, 10, 128) (10, 10, 10, 128) (10, 10, 10, 128) 
(4, 10, 10, 10, 128)


In [7]:
y.shape

TensorShape([4, 8, 7, 6, 32])

In [ ]:
# 만약에 850x850 크기의 이미지와 3개의 채널을 입력값으로 가지는 ConvLSTM2D 를 만들어야 하면 아래와 같이 코드 작성

from syslog import LOG_SYSLOG


model = Sequential()
model.add(ConvLSTM2D(filters=40, 
                     kernel_size=(3,3), 
                     input_shape=(None,850,850,3), 
                     padding="same", 
                     return_sequences=True))
model.add(BatchNormalization())
model.add(ConvLSTM2D(filters=40, 
                     kernel_size=(3,3), 
                     padding="same", 
                     return_sequences=True))
model.add(BatchNormalization())
model.add(ConvLSTM2D(filters=40, 
                     kernel_size=(3,3), 
                     padding="same", 
                     return_sequences=True))
model.add(BatchNormalization())
model.add(ConvLSTM2D(filters=40, 
                     kernel_size=(3,3), 
                     padding="same", 
                     return_sequences=True))
model.add(BatchNormalization())
model.add(ConvLSTM2D(filters=40, 
                     kernel_size=(3,3), 
                     padding="same", 
                     return_sequences=True))
model.add(BatchNormalization())
model.add(Conv3D(filters=1, 
                 kernel_size=(3,3,3), 
                 activation="sigmoid",
                 padding="same"))
model.compile(loss='binary_crossentropy',optimizer='adadelta')
model.summary()


/Volumes/looparam/#1 Coding/#10 Python/AcademicFestival/AF/lib/python3.10/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv_lstm2d (ConvLSTM2D)        │ (None, None, 850, 850, │        62,080 │
│                                 │ 40)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, None, 850, 850, │           160 │
│ (BatchNormalization)            │ 40)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_lstm2d_1 (ConvLSTM2D)      │ (None, None, 850, 850, │       115,360 │
│                                 │ 40)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, None, 850, 850, │           160 │
│ (BatchNormalization)            │ 40)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_lstm2d_2 (ConvLSTM2D)      │ (None, None, 850, 850, │       115,360 │
│                                 │ 40)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, None, 850, 850, │           160 │
│ (BatchNormalization)            │ 40)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_lstm2d_3 (ConvLSTM2D)      │ (None, None, 850, 850, │       115,360 │
│                                 │ 40)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, None, 850, 850, │           160 │
│ (BatchNormalization)            │ 40)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_lstm2d_4 (ConvLSTM2D)      │ (None, None, 850, 850, │       115,360 │
│                                 │ 40)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, None, 850, 850, │           160 │
│ (BatchNormalization)            │ 40)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3d_1 (Conv3D)               │ (None, None, 850, 850, │         1,081 │
│                                 │ 1)                     │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 525,401 (2.00 MB)

 Trainable params: 525,001 (2.00 MB)

 Non-trainable params: 400 (1.56 KB)